### Cadastrar um novo produto
POST http://localhost:3333/products
Content-Type: application/json

{
  "name": "produto 3",
  "description": "Descrição 1",
  "price": 249.90,
  "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4gO8tCIezFmKIjwUlRF2aT-zG8N_T47HQMw&s",
  "isNew": true
}

### Buscar todos os produtos
GET http://localhost:3333/products